# Generated by Django 4.2.1 on 2025-05-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='bike',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['-time_create'], name='bikesharing_time_cr_8bae6b_idx'),
        ),
    ]
