# Generated by Django 5.2 on 2025-05-31 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikesharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bike',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='bikesharing.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='bike',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man', to='bikesharing.manufacturer', verbose_name='Завод'),
        ),
        migrations.AddField(
            model_name='bike',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='bikesharing.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['-time_create'], name='bikesharing_time_cr_8bae6b_idx'),
        ),
    ]
