# Generated by Django 5.2 on 2025-05-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0003_category_alter_bike_is_published_alter_bike_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikesharing.category'),
        ),
    ]
