# Generated by Django 4.2.1 on 2025-05-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0005_tagpost_alter_bike_cat_bike_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='bikesharing.tagpost', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='bike',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man', to='bikesharing.manufacturer'),
        ),
    ]
