# Generated by Django 4.2.1 on 2025-05-26 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0006_manufacturer_alter_bike_tags_bike_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['-time_create'], 'verbose_name': 'Аренда транспорта', 'verbose_name_plural': 'Аренда транспорта'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Различные тарифы', 'verbose_name_plural': 'Различные тарифы'},
        ),
        migrations.AlterField(
            model_name='bike',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='bikesharing.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=1, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man', to='bikesharing.manufacturer', verbose_name='Завод'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
